### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by michaeljcoyne** [bbottema/d3-tag-skills-cloud#1]
You are missing the html tag in the document, the ending body tag and the meta tag should be between the head tags.

Also quite frequently it doesn't display - I am assuming that it doesn't fit - but there are only 3 words.

**Comment by bbottema** [comment]
hmm, that is quite odd. That's not how I remember the code to be.

I'll look into it.

**Comment by michaeljcoyne** [comment]
Also get this error when blank:
 mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by michaeljcoyne** [comment]
Sorry that console comes up all the time. But interestingly when it is blank there is no Retrying in the console. So the script might assume that everything is ok.

**Comment by bbottema** [comment]
Ahh, I found out what the issue is. Aside from the strange HTML markup, it works if you do an `npm install` first. That retrieves the D3 dependencies needed for the demo. For that you need NodeJs and NPM installed.

I'll just added the node_modules folder to version control, so you don't have to bother with nodejs and npm. One sec.

**Comment by bbottema** [comment]
Alright, @michaeljcoyne, can you update and try again?

**Comment by michaeljcoyne** [comment]
It definitely works better but with Firefox it does give a blank screen about 2 or three times out of 10 with no console message. (I haven't tried other browsers yet)

**Comment by bbottema** [comment]
I have no idea why it would be blank. I've also seen it a couple of times when refreshing the page. I don't have time to dig into that one though. 

It might be a D3 issue, where you have to wait for the DOM to finish loading or something before drawing the cloud.

**Comment by michaeljcoyne** [comment]
It's weird actually you can see the code is there but it isn't rendering so could be a html 5 issue too.

**Comment by michaeljcoyne** [comment]
Seems to be more consistent if u do this   generateSkillCloud( 0 );
On the first time it loads.

**Comment by michaeljcoyne** [comment]
Might be nice to find out how Jason got it to animate on load also.

**Comment by michaeljcoyne** [comment]
It also doesn't load when all the values are the same.

**Comment by michaeljcoyne** [comment]
I think I miss-understood what this project aims to do - I thought it calculates weighting by values - but it doesn't. As if relevance and years are the same the sizes of the font are different and so is the space it uses up. That is usually what a tag cloud would do.    var minyears = _.min(_.map(skills, 'years'))-1; fixes the above issue btw.

**Comment by michaeljcoyne** [comment]
sorry it does make them the same size - I thought it didn't

**Comment by bbottema** [comment]
Everything ok, @michaeljcoyne?
